name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  PYTHON_VERSION: '3.12'

jobs:
  lint-and-test:
    name: Call Lint and Test
    uses: ./.github/workflows/lint-and-test.yml

  build-and-release:
    needs: lint-and-test
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install .
      - name: Build the package
        run: python -m pip install build && python -m build
      - name: Check Version
        id: check-version
        run: |
          [[ "$(grep 'version =' pyproject.toml | sed 's/version = "\(.*\)"/\1/')" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ steps.check-version.outputs.prerelease == 'true' }}
